include ./gruvbox_light.conf

# Cursor
cursor #3c3836

# Shell
shell /usr/bin/fish

# Font
font_family Iosevka Nerd Font
font_size 18

# Padding (kitty uses window_padding_width)
window_padding_width 10

# Cursor style
cursor_shape block
cursor_blink_interval 0

# Keep block cursor at shell prompt
shell_integration no-cursor

# Confirm close when programs are running
confirm_os_window_close 0

url_color #076678
linux_display_server wayland
